server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 也是30天过期
    session:
      cookie:
        max-age: 2592000

spring:
  application:
    name: yu-picture-backend
    # 数据库 配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.103:3306/yu_picture?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123456

  # Redis 配置
  redis:
    database: 0
    host: 192.168.0.103
    port: 6379
    timeout: 5000
    password: 123456

  # Session 配置
  session:
    store-type: redis
    # session 30天后过期
    timeout: 2592000

  # servlet配置 - 开放更大的文件上传体积
  servlet:
    multipart:
      max-file-size: 10MB

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    # 仅在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除字段 -> 不会直接删除数据，而是把is_delete字段设置为1，0表示未删除，1表示已删除
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为0)

# Knife4j - 接口文档配置
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: v1.0
    # 最重要的配置 - 接口分组
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.yupi.yupicturebackend.controller # 接口位置为controller包

